version: '3'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    volumes:
      - "./backend/:/usr/src/app/"
  mongodb:
    image: "mongo"
    container_name: "family-planner-db"
    volumes:
      - ./backend/mongo-volume:/data-db
    ports:
      - "27017:27017"
  frontend:
    image: svelte-template:dev
    build:
      context: ./frontend
    volumes:
      - "./frontend:/app"
    ports:
      - "3000:3000"
      - "35729:35729"